Switch to new promotion authoring
hlxsites/famous-smoke-cigaradvisor pull request #216
Opened 2024-02-07 10:15 UTC by Kronnox

Fix #202

Instead of managing the promotion content in the spreadsheet, the speadsheet (promotions.xlsx) is now only used for scheduling. The promotion content is generic (however, in the current use case only the ImageCTA block is used) and authored as fragments (could really be located anywhere but I chose /fragments/promotions/).

Fun fact: This also enables promotions with rotating images on their own, so rotating promotions with rotating images 🎉

Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
- After: https://issue-202--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor

2024-02-07 13:36 UTC, tmaret submitted a review, later dismissed

2024-02-07 15:27 UTC, bstopp approved these changes

2024-02-07 16:36 UTC, kailasnadh790 submitted a review, later dismissed

2024-02-07 17:23 UTC, bstopp requested changes
Something odd is happening - the section is being marked as loaded before this block is finished with its work.

2024-02-07 17:28 UTC, kailasnadh790 commented
also, observed a height difference
![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/50a89cc4-1873-45e8-86a8-163e70c04d3d)

2024-02-07 18:05 UTC, bstopp commented
yeah, that's related to the same bug i'm seeing. SHould have a fix soon.

2024-02-07 19:34 UTC, kailasnadh790 approved these changes

2024-02-08 08:13 UTC, Kronnox commented
> Something odd is happening - the section is being marked as loaded before this block is finished with its work.

@bstopp Ofc you're absolutely right with this one. Somehow forgot, that EDS doesn't like async handling anymore on the blocks. I'll commit some minor changes for readability

2024-02-08 13:42 UTC, bstopp commented on cigaradvisor/blocks/promotion-banner/promotion-banner.js
> +  return fragment ? fragment.querySelector('main > .section > div:first-of-type > div:first-of-type') : null;
```suggestion
  return fragment ? fragment.querySelector('main > .section .block') : null;
```

2024-02-08 13:44 UTC, bstopp commented on cigaradvisor/blocks/promotion-banner/promotion-banner.js
> +    if (content) block.parentElement.replaceWith(content);
I'm somewhat torn on this. This replaces the wrapper with the block - removing the wrapper element from the original dom. I know i put this here, and it is a fix for making sure this CTA is the same height as the other column. but i wonder if there's a css-only way to fix this w/ layout handling.

2024-02-15 15:36 UTC, bstopp approved these changes

2024-02-15 15:36 UTC, merged