Feat/article rec
hlxsites/famous-smoke-cigaradvisor pull request #226
Opened 2024-02-21 18:36 UTC by kailasnadh790

Fix #225 

Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/category/cigar-reviews/my-weekend-cigar-review-red-meat-lovers-filet-mignon
- After: https://feat-article-rec--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/category/cigar-reviews/my-weekend-cigar-review-red-meat-lovers-filet-mignon

2024-02-21 18:48 UTC, bstopp requested changes
Can you make the "you may also like..." part of this block?

2024-02-21 19:59 UTC, kailasnadh790 commented
heading added.

2024-02-22 15:45 UTC, bstopp approved these changes

2024-02-22 15:46 UTC, bstopp requested changes

2024-02-22 15:46 UTC, bstopp commented on cigaradvisor/scripts/templates/blog-post.js
> +  const randomPost = posts.filter((post) => !authorPosts.includes(post) && !categoryPosts.includes(post) && post.path !== window.location.pathname);
This is supposed to be 1 random post from the list on the _Must Reads_ page. not one random from anywhere.

2024-02-22 16:52 UTC, merged