Feature/image cta
hlxsites/famous-smoke-cigaradvisor pull request #31
Opened 2023-11-30 17:40 UTC by kailasnadh790

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Issue: https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/7

Test URLs:
- https://feature-image-cta--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/drafts/Kailas/image-cta

2023-12-01 13:34 UTC, tmaret approved these changes

2023-12-01 20:32 UTC, bstopp commented
I'd like to get `picture` element to pre-save the space for the image, which will be lazy loaded. Without this we'll end up with CLS issues if the block is marked as finished, but then the image loads after other, subsequent, blocks.

This can be done with two steps:

1. Set the `picture` to be relative position, then absolute position the image within it. [Example CSS](https://github.com/hlxsites/takeda-ihs/blob/82e064c17103a3f629684b8dfedd862b338beb79/blocks/cards/cta.css#L35-L50) 
1. Calculate the width-to-height ratio. Then add this as padding (bottom or top). This creates the space in which the Image will fit when rendered. [Example JS](https://github.com/hlxsites/takeda-ihs/blob/82e064c17103a3f629684b8dfedd862b338beb79/blocks/cards/cta.js#L19-L21).
   1. This step should also set the max-width based on the original image's width. This way the image doesn't grow larger than desired, which can result in pixelation.

2023-12-01 20:33 UTC, bstopp requested changes
I'd like to get `picture` element to pre-save the space for the image, which will be lazy loaded. Without this we'll end up with CLS issues if the block is marked as finished, but then the image loads after other, subsequent, blocks.

This can be done with two steps:

1. Set the `picture` to be relative position, then absolute position the image within it. [Example CSS](https://github.com/hlxsites/takeda-ihs/blob/82e064c17103a3f629684b8dfedd862b338beb79/blocks/cards/cta.css#L35-L50) 
1. Calculate the width-to-height ratio. Then add this as padding (bottom or top). This creates the space in which the Image will fit when rendered. [Example JS](https://github.com/hlxsites/takeda-ihs/blob/82e064c17103a3f629684b8dfedd862b338beb79/blocks/cards/cta.js#L19-L21).
   1. This step should also set the max-width based on the original image's width. This way the image doesn't grow larger than desired, which can result in pixelation. 
   

This is an example I've used to do this same approach for the free-form images in long form pages:

* [Example JS](https://github.com/hlxsites/takeda-ihs/blob/82e064c17103a3f629684b8dfedd862b338beb79/scripts/scripts.js#L157-L165)
* [Picture CSS](https://github.com/hlxsites/takeda-ihs/blob/82e064c17103a3f629684b8dfedd862b338beb79/styles/styles.css#L300-L306)
* [Img CSS](https://github.com/hlxsites/takeda-ihs/blob/82e064c17103a3f629684b8dfedd862b338beb79/styles/styles.css#L316-L324)

2023-12-04 17:26 UTC, kailasnadh790 reviewed
changes applied

2023-12-04 18:49 UTC, bstopp approved these changes

2023-12-04 18:50 UTC, merged