imagecta link fix
hlxsites/famous-smoke-cigaradvisor pull request #41
Opened 2023-12-07 20:08 UTC by kailasnadh790

issue: https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/11

Test URLs:
- https://feature-two-column-section--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/drafts/Kailas/two-col-video

2023-12-07 20:22 UTC, bstopp requested changes

2023-12-07 21:35 UTC, kailasnadh790 commented on cigaradvisor/blocks/imagecta/imagecta.js
> +  const link = block.querySelector('a').getAttribute('href');
added title with image's alt value.

2023-12-07 23:24 UTC, kailasnadh790 commented on cigaradvisor/scripts/scripts.js
> +  const anchor = document.createElement('a');
fixed

2023-12-08 19:11 UTC, bstopp requested changes

2023-12-08 19:11 UTC, bstopp commented on cigaradvisor/styles/styles.css
> +  main .two-column-section[data-layout="50/50"] .imagecta.block>a img {
Global styling shouldn't have block-level declarations.

if the block needs to change based on a wrapping context, move this to that CSS file.

i.e:  It's ok for a block to put global qualifiers in its CSS, it's not ok for a Global CSS to use any `.block` qualifiers

2023-12-11 16:21 UTC, bstopp approved these changes

2023-12-11 17:05 UTC, merged