carousel fix
hlxsites/famous-smoke-cigaradvisor pull request #73
Opened 2024-01-16 16:44 UTC by kailasnadh790

Fix https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/72

Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/drafts/Kailas/homepage
- After: https://feature-homepage--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/drafts/Kailas/homepage

2024-01-16 20:43 UTC, kailasnadh790 commented
@bstopp This PR has global styling for buttons and Section headings as well.

2024-01-16 20:44 UTC, bstopp commented
Was there not 2 issues being fixed with this one PR?

2024-01-16 22:05 UTC, kailasnadh790 commented
@bstopp I had captured them as tasks under one issue https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/72 .
Let me know if I need to create separate issues and separate the PRs. Sorry for the confusion.

2024-01-16 22:22 UTC, bstopp requested changes

2024-01-16 22:22 UTC, bstopp commented on cigaradvisor/blocks/carousel/carousel.css
> +  font-size: x-large;
What does `x-large` mean? Let's be specific - either a variable or a px size (variable preferred if we have one)

2024-01-16 22:22 UTC, bstopp commented on cigaradvisor/blocks/carousel/carousel.js
> +        block.querySelector('.arrow-prev').style.display = 'flex';
we shouldn't set literal styles on the elements. Should add a class which will set `display: none` as an override to the `display: flex` on the element.

2024-01-16 22:22 UTC, bstopp commented on cigaradvisor/styles/styles.css
> +    background: url('/cigaradvisor/images/homepage/sectiontitle/media_10c44610cd58523f02bbd64b114069404ca081e41.png') center no-repeat;
if it's in the CSS - it should probably come from the codebase, not from the media-bus

2024-01-16 22:22 UTC, bstopp commented on cigaradvisor/styles/styles.css
> +  color: #fff;
use variables

2024-01-16 22:22 UTC, bstopp commented on cigaradvisor/styles/styles.css
> +  --section-background: #eaeaea;
What color is this? `section-background` isn't clear - in the context of the use (below) it's for a section with a grey background, let's make that the variable name.

2024-01-17 13:31 UTC, bstopp approved these changes

2024-01-17 14:51 UTC, merged